using System;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.Playwright;

namespace BackloggdMirror.Services;

/// <summary>
/// Which anti-bot protection stopped us.
/// </summary>
internal enum AntiBotProtection
{
    /// <summary>Anubis / BotStopper (Techaro), the one Backloggd uses today.</summary>
    Anubis,

    /// <summary>Bunny Shield, bunny.net's WAF (Backloggd is served behind BunnyCDN).</summary>
    BunnyShield,

    /// <summary>Cloudflare challenge ("Just a moment...").</summary>
    Cloudflare,

    /// <summary>
    /// Something intercepted us but we cannot tell what: the response is not a Backloggd page.
    /// Covers protections that do not have a signature here yet.
    /// </summary>
    Unknown
}

/// <summary>A single interception, carrying just enough to leave a trace in the log.</summary>
internal sealed class AntiBotBlock
{
    public AntiBotBlock(AntiBotProtection protection, string url, string pageTitle)
    {
        Protection = protection;
        Url = url;
        PageTitle = pageTitle;
    }

    public AntiBotProtection Protection { get; }
    public string Url { get; }
    public string PageTitle { get; }

    public override string ToString() =>
        $"blocked by {Protection} at '{Url}' (page title: '{PageTitle}')";
}

/// <summary>
/// Recognises the anti-bot screens that arrive instead of the requested content.
///
/// It exists because these protections do NOT announce themselves through the status code: Anubis
/// answers 200 OK with an "access denied" page, so a <c>response.Status == 403</c> check never sees
/// them and the failure ends up disguised as "no results" or as a selector timeout.
///
/// Only consulted once something has already failed (an expired WaitForSelector, a navigation that
/// did not land where expected). Looking solely at the error path avoids mistaking a transient
/// challenge, which clears itself within a couple of seconds, for a real block.
/// </summary>
internal static class AntiBotDetection
{
    /// <summary>
    /// Markers present on EVERY page served by the Backloggd application, including its own 404
    /// pages. If not one of them is there, what we are looking at was not generated by Backloggd.
    /// </summary>
    private static readonly string[] BackloggdMarkers = { "nav-bar-search", "csrf-token" };

    /// <summary>
    /// Per-protection signatures. They exist to name the block in the log, not as the safety net:
    /// if a protection changes its marks or a new one appears, the block is still caught by the
    /// absence of <see cref="BackloggdMarkers"/> and reported as
    /// <see cref="AntiBotProtection.Unknown"/>.
    /// </summary>
    private static readonly (AntiBotProtection Protection, string[] Signatures)[] KnownProtections =
    {
        (AntiBotProtection.Anubis, new[]
        {
            "anubis_version",
            "within.website/x/cmd/anubis",
            "botstopper"
        }),
        (AntiBotProtection.BunnyShield, new[]
        {
            "bunny-shield",
            "bunnyshield",
            "shield.bunny.net",
            "bunnycdn shield"
        }),
        (AntiBotProtection.Cloudflare, new[]
        {
            "cf-browser-verification",
            "challenge-platform",
            "cf_chl_opt",
            "just a moment..."
        })
    };

    private static readonly Regex TitleRegex =
        new(@"<title[^>]*>(.*?)</title>", RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    /// <summary>
    /// Inspects whatever is on the page right now. Returns null if it does not look like a block.
    /// Never throws: it runs from catch blocks and must not mask the original error.
    /// </summary>
    public static async Task<AntiBotBlock?> DetectAsync(IPage page)
    {
        try
        {
            return Detect(await page.ContentAsync(), page.Url);
        }
        catch
        {
            // The page may have closed or be mid-navigation; with no HTML there is nothing to say.
            return null;
        }
    }

    /// <summary>
    /// Pure version, over HTML that has already been fetched.
    /// </summary>
    public static AntiBotBlock? Detect(string? html, string url)
    {
        if (string.IsNullOrWhiteSpace(html)) return null;

        var lower = html.ToLowerInvariant();

        foreach (var (protection, signatures) in KnownProtections)
        {
            foreach (var signature in signatures)
            {
                if (lower.Contains(signature, StringComparison.Ordinal))
                {
                    return new AntiBotBlock(protection, url, ExtractTitle(html));
                }
            }
        }

        foreach (var marker in BackloggdMarkers)
        {
            // One match is enough: the page is Backloggd's and the failure is something else
            // (changed selector, profile with no entries, search with no results...).
            if (lower.Contains(marker, StringComparison.Ordinal)) return null;
        }

        return new AntiBotBlock(AntiBotProtection.Unknown, url, ExtractTitle(html));
    }

    private static string ExtractTitle(string html)
    {
        var match = TitleRegex.Match(html);
        if (!match.Success) return "(no title)";

        var title = match.Groups[1].Value.Trim();
        return title.Length > 120 ? title.Substring(0, 120) + "…" : title;
    }
}
